### ISSUE TITLE
Add IJavascript kernel

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/jupyter-docker#10]
The [IJavascript kernel](http://n-riesco.github.io/ijavascript/) adds Node.js support.

Partial installation instructions for Alpine, as far as I can figure:

```
apk add nodejs-lts
npm install -g node-uuid ijavascript
ijs --ijs-install=global
```

While this lets you open a new Javascript notebook in Jupyter, the kernel dies pretty quickly.

**Comment by fenwanderer** [comment]
If you follow the above instructions, when you run an IJavascript kernel, Jupyter spits this out to the console:

```
[I 21:09:45.448 NotebookApp] Kernel started: b91de2f8-dbdf-43bc-87c4-2320734329a3
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at parseCommandArguments (/usr/lib/node_modules/ijavascript/lib/kernel.js:180:36)
    at Object.<anonymous> (/usr/lib/node_modules/ijavascript/lib/kernel.js:44:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

This may be because the global install isn't quite working:

```
bash-4.3# npm install -g ijavascript
/
> zmq@2.15.3 install /usr/lib/node_modules/ijavascript/node_modules/jp-kernel/node_modules/jmp/node_modules/zmq
> node-gyp rebuild

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/4.4.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ijavascript/node_modules/jp-kernel/node_modules/jmp/node_modules/zmq/.node-gyp"
make: Entering directory '/usr/lib/node_modules/ijavascript/node_modules/jp-kernel/node_modules/jmp/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc: In destructor 'zmq::Socket::IncomingMessage::MessageReference::~MessageReference()':
../binding.cc:999:54: warning: throw will always call terminate() [-Wterminate]
               throw std::runtime_error(ErrorMessage());
                                                      ^
../binding.cc:999:54: note: in C++11 destructors default to noexcept
../binding.cc: In destructor 'zmq::Socket::OutgoingMessage::~OutgoingMessage()':
../binding.cc:1205:50: warning: throw will always call terminate() [-Wterminate]
           throw std::runtime_error(ErrorMessage());
                                                  ^
../binding.cc:1205:50: note: in C++11 destructors default to noexcept
  SOLINK_MODULE(target) Release/obj.target/zmq.node
  COPY Release/zmq.node
make: Leaving directory '/usr/lib/node_modules/ijavascript/node_modules/jp-kernel/node_modules/jmp/node_modules/zmq/build'
/usr/bin/ijs -> /usr/lib/node_modules/ijavascript/bin/ijavascript.js
ijavascript@5.0.13 /usr/lib/node_modules/ijavascript
└── jp-kernel@0.0.1 (nel@0.5.0, jmp@0.4.0)
```

The `/root/.node-gyp` directory it first tries to access does not exist.  Continuing investigating using nodejs/node-gyp/issues/454...

**Comment by jeffyjefflabs** [comment]
This sequence worked for me.  I get the same output from the npm install, but the kernel works.

```
apk add nodejs
npm install -g ijavascript
ijs --ijs-install=global
```
